### ISSUE TITLE
Error to json marshal MessageEntity

### ISSUE THREAD

**Issue by topjedi** [NicoNex/echotron#13]
Looks like misprint, all json fields are in lower case https://core.telegram.org/bots/api#messageentity. Type 'MessageEntity' has error in Length field
types.go:278:
``Length int    `json:"Length"` ``

**Comment by topjedi** [comment]
fix https://github.com/NicoNex/echotron/pull/14

**Comment by DjMike238** [comment]
> Looks like misprint, all json fields are in lower case https://core.telegram.org/bots/api#messageentity. Type 'MessageEntity' has error in Length field
> types.go:278:
> `` Length int `json:"Length"` ``

Good catch! Merging it right now.
