### ISSUE TITLE
How send file( photo ,audio,video,doc) by url (like google cloud storage)

### ISSUE THREAD

**Issue by jmy2022** [NicoNex/echotron#27]
now ,I just find two way 
1. echotron.NewInputFilePath("assets/tests/echotron_test.png"),
2. echotron.NewInputFileID(photoID),

I need new way by url

**Comment by DjMike238** [comment]
Hey there! Looks like we missed this feature in the Telegram API docs. We'll look into it!

**Comment by DjMike238** [comment]
Hello! `echotron.NewInputFileURL()` is now available on version v3.23.1. Thanks for the heads up!
