### ISSUE TITLE
Wrong ChatID after marshaling 

### ISSUE THREAD

**Issue by vildan-valeev** [NicoNex/echotron#29]
I wrote couple tests for CommandOptions type for setMyCommands method...

https://github.com/vildan-valeev/hotron/blob/master/querybuilder_test.go#L36

When **ChatID** is 0101010, after  call **scan()** func and getting **url.Values**, chat_id will be 0101010, but it's - 33288.

**Comment by NicoNex** [comment]
The problem here is that when you write 0101010 since it starts with a 0 Go lexer assumes that it's a number with base 8, in fact 0101010 base 8 equals to 33288 base 10.
So everything is working as expected.
