### ISSUE TITLE
meet error `unexpected EOF`

### ISSUE THREAD

**Issue by feitian124** [NicoNex/echotron#32]
hi, thank you open sourced this great project. I used it in my project https://github.com/feitian124/ai-tg-bot.
but sometime it will report `unexpected EOF` error and i did not find the reason.

it maybe the network issue but i tried another python based project it works great, so i report here see if any other encounter similiar problem. thanks.

below is the code report error:

https://github.com/feitian124/ai-tg-bot/blob/1ceefaa6839f231913116caf407bee9a005811d2/bot/bot.go#L39

```
❯ go version
go version go1.20 linux/amd64
❯ uname -a
Linux ming-manjaro 5.15.94-1-MANJARO #1 SMP PREEMPT Tue Feb 14 19:45:58 UTC 2023 x86_64 GNU/Linux
```

```
2023/03/09 23:59:16 openai.go:30: call openai 66
2023/03/09 23:59:42 openai.go:30: call openai 12
2023/03/09 23:59:43 openai.go:30: call openai 13
2023/03/09 23:59:45 openai.go:30: call openai 14
2023/03/09 23:59:47 openai.go:30: call openai 15
2023/03/09 23:59:52 openai.go:30: call openai 16
2023/03/09 23:59:52 openai.go:38: error, status code: 429, message: Rate limit reached for default-gpt-3.5-turbo in organization org-37swCbTzJXHN64Hwy1jxeyLR on requests per min. Limit: 20 / min. Current: 30 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.
2023/03/09 23:59:53 telegram.go:60: error: API error: 400 Bad Request: message text is empty
2023/03/10 00:00:32 bot.go:39: Get "https://api.telegram.org/bot****/getUpdates?offset=917512766&timeout=120": unexpected EOF
```

**Comment by Ldsu** [comment]
我自己项目也报这个错....
Error occurred in network.go/sendGetRequest http.get

[https://dpjeep.com/2019/06/10/golangzhi-http-eofxiang-jie/
https://qa.1r1g.com/sf/ask/1240014611/](https://stackoverflow.com/questions/17714494/golang-http-request-results-in-eof-errors-when-making-multiple-requests-successi)

**Comment by DjMike238** [comment]
> hi, thank you open sourced this great project.

Thank you for your kind words!

> below is the code report error:
> https://github.com/feitian124/ai-tg-bot/blob/1ceefaa6839f231913116caf407bee9a005811d2/bot/bot.go#L39

**Comment by DjMike238** [comment]
> hi, thank you open sourced this great project.

Thank you for your kind words, @feitian124!

> sometime it will report unexpected EOF error and i did not find the reason.

Judging by the logs you sent, while trying to poll Telegram for new updates, it's possible that Telegram's servers return an empty response.

Nevertheless, I'll keep an eye on this issue, since currently I can't seem to replicate it.

Anyway, I took the liberty to look around the repo you linked, and I have two suggestions for you:
1. After https://github.com/feitian124/ai-tg-bot/blob/1ceefaa6839f231913116caf407bee9a005811d2/bot/telegram.go#L57, you might want to check the `err` value, to avoid trying to send an empty message (which, as you can see by the logs you sent, just doesn't work).
2. In `bot.go`, you might want to initialize and call the dispatcher in a way similar to the [Long Polling example in Echotron's readme](https://github.com/NicoNex/echotron#long-polling-1). That ensures that the dispatcher is restarted automatically in case there's any issue, preventing the bot from crashing.

**Comment by DjMike238** [comment]
> 我自己项目也报这个错....

@Ldsu, for ease of communicating, I kindly ask you to write your future comments in English.

**Comment by feitian124** [comment]
@DjMike238 thank you for your advises, both very helpful, i will check.

**Comment by NicoNex** [comment]
I'd like to remark the second point expressed by @DjMike238 for sake of documentation.
The dispatcher might return an error mostly due to network issues or other exceptions such as yours.
But as the good Rob Pike teaches us, the error in Go is just a value, so it's completely safe to simply restart the polling process if it terminates.

This can be done simply with a loop:
```golang
for {
    log.Println(dsp.Poll())
    // For network issues it's better to wait a bit before retrying.
    time.Sleep(5 * time.Second)
}
```

**Comment by feitian124** [comment]
@NicoNex  thank you for clarify.
I updated my code as per @DjMike238 suggestion and played a while. I believe i found the partial reason.
when i send **english** text it do not report error for a long time, but if i send **chinese** text it report error in a short time.

```
2023/03/10 10:19:32 openai.go:30: ask openai: hello
2023/03/10 10:19:33 openai.go:39: openai answer: Hello! How can I assist you today?
2023/03/10 10:19:48 openai.go:30: ask openai: 1+1=?
2023/03/10 10:19:49 openai.go:39: openai answer: The sum of 1 and 1 is 2.
2023/03/10 10:20:06 openai.go:30: ask openai: 1+2+3+...+100=?
2023/03/10 10:20:09 openai.go:39: openai answer: The sum of the first 100 positive integers can be calculated as:

1 + 2 + 3 + .... + 100 = (100 * 101) / 2 = 5050

Therefore, the sum of the first 100 positive integers is 5050.
2023/03/10 10:20:36 openai.go:30: ask openai: what year as of now
2023/03/10 10:20:38 openai.go:39: openai answer: As an AI language model, I do not have direct access to real-time information. However, as of my last training data update, the current year is 2021.
2023/03/10 10:20:49 openai.go:30: ask openai: are you sure?
2023/03/10 10:20:52 openai.go:39: openai answer: As an AI language model, I don't have access to the current date or time, but I was last trained on updated data in 2021, which means I am quite confident that the current year is 2021 or later.
2023/03/10 10:21:19 openai.go:30: ask openai: but as i know current year is 2023
2023/03/10 10:21:21 openai.go:39: openai answer: I apologize for the confusion earlier. As an AI language model, I do not have access to real-time information, and my responses are generated based on the data I was last trained on. If the current year is indeed 2023, then I stand corrected.
2023/03/10 10:21:46 openai.go:30: ask openai: what year now?
2023/03/10 10:21:48 openai.go:39: openai answer: As an AI language model, I do not have access to real-time information. However, based on my last training data update, the current year, as of 2021, is 2021. If there have been changes to the current year since then, I may not be aware of them.
2023/03/10 10:22:07 openai.go:30: ask openai: 你好
2023/03/10 10:22:08 openai.go:39: openai answer: 你好！有什么我能帮助你的吗？
2023/03/10 10:22:40 bot.go:40: error: Get "https://api.telegram.org/bot***/getUpdates?offset=917512790&timeout=120": unexpected EOF
```

**Comment by Ldsu** [comment]
The error occur in network.go/sendGetRequest http.get

https://stackoverflow.com/questions/17714494/golang-http-request-results-in-eof-errors-when-making-multiple-requests-successi
