### ISSUE TITLE
Method restrictChatMember doesn't work if ChatPermissions are wrapped with PermissionOptions

### ISSUE THREAD

**Issue by dpogibenko** [NicoNex/echotron#34]
Hello!
I've faced a problem with applying user permissions. 
Function `restrictChatMember` from api.go uses function `serializePerms` where struct `ChatPermissions` is wrapped with `PermissionOptions`.

Output looks like this and such representation is ignored by telegram server:
`permissions={"permissions":{"can_send_messages":true}}`

If I change code so ChatPermissions isn't wrapped it works well:
`permissions={"can_send_messages":true}`

This code doesn't work for me:

    func serializePerms(permissions ChatPermissions) (string, error) {
	    perm, err := json.Marshal(PermissionOptions{permissions})
	    if err != nil {
		    return "", err
	    }
	    return string(perm), nil
    }

And this works:

    func serializePerms(permissions ChatPermissions) (string, error) {
	    perm, err := json.Marshal(permissions)
	    if err != nil {
		    return "", err
	    }
	    return string(perm), nil
    }

Is it bug or my mistake?

**Comment by DjMike238** [comment]
Hi @dpogibenko, I'm really sorry for the really late answer, but things happened and I only just now managed to check this issue.

I just pushed the fix (fabc7ad), it is now available in the latest version of Echotron, `v3.27.0`.

Thanks for the heads up!
