### ISSUE TITLE
Can API methods be called concurrently?

### ISSUE THREAD

**Issue by JoshuaDietz** [NicoNex/echotron#36]
Hi,
I just wanted to make sure if API Methods like `SendMessage` or `BanChatMember` can be called concurrently? I took a quick look on the source code and it looks like they can but by go convention this should be documented for methods, which it is not. That's why I wanted to make sure.

Kind regards
Joshua

**Comment by NicoNex** [comment]
Hi, yes all API methods can definitely be called concurrently.
Also thanks for the tip, we will document the feature.
